default: &default
  adapter: postgresql
  encoding: unicode
  pool: "{{ DB_POOL | default(5) }}"
  timeout: "{{ DB_TIMEOUT | default(5000) }}"

development:
  <<: *default
  # Use DATABASE_URL if provided, otherwise build from components
  url: "{{ DATABASE_URL | default('') }}"
  database: "{{ DB_NAME | default('todosapp_development') }}"
  username: "{{ DB_USERNAME | default('') }}"
  password: "{{ DB_PASSWORD | default('') }}"
  host: "{{ DB_HOST | default('localhost') }}"
  port: "{{ DB_PORT | default(5432) }}"

test:
  <<: *default
  database: "{{ DB_NAME | default('todosapp_test') }}"
  username: "{{ DB_USERNAME | default('') }}"
  password: "{{ DB_PASSWORD | default('') }}"
  host: "{{ DB_HOST | default('localhost') }}"
  port: "{{ DB_PORT | default(5432) }}"

production:
  <<: *default
  database: "{{ DB_NAME | default('todosapp_production') }}"
  username: "{{ DB_USERNAME }}"
  password: "{{ DB_PASSWORD }}"
  host: "{{ DB_HOST | default('localhost') }}"
  port: "{{ DB_PORT | default(5432) }}"
  # Additional production settings
  pool: "{{ DB_POOL | default(20) }}"
  timeout: "{{ DB_TIMEOUT | default(10000) }}"
